apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-db
  labels:
    {{- include "app.labels" . | nindent 4 }}
stringData:
  rootUser: root
  rootHost: '%'
  rootPassword: root
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: {{ include "app.fullname" . }}-db
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  name: {{ include "app.fullname" . }}-db
  instances: 1
  router:
    instances: 1
  tlsUseSelfSigned: true