name: 'ECA Config'
type: module
description: 'Config events.'
core_version_requirement: ^9 || ^10
package: ECA
dependencies:
  - eca:eca

# Information added by Drupal.org packaging script on 2023-07-14
version: '1.1.4'
project: 'eca'
datestamp: 1689338283
